#
# docker-compose.dev.yml
#
version: "3.8"
services:

  api-service:
    container_name: api-services
    build:
      context: ./
      dockerfile: ./api_service/Dockerfile
    ports:
      - 8000:80
    restart: unless-stopped
    command: "uvicorn api_service.main:fastapi --reload --port 80 --host 0.0.0.0"
    volumes:
      - .:/netorc/
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M

  redis:
    container_name: netorc-redis
    image: redis:6.2-bullseye
    restart: unless-stopped
    depends_on:
      - api-services
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M

  postgres:
    container_name: netorc-postgres
    image: postgres:15.2-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: netorc
      POSTGRES_PASSWORD: netorc123
      POSTGRES_DB: netorc
    ports:
      - 5432:5432
    depends_on:
      - api-services
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M

  worker-service:
    container_name: worker-services
    build:
      context: ./
      dockerfile: ./worker_service/Dockerfile
    command: "watchmedo auto-restart -d worker_service/ -p '*.py' --recursive -- celery -A miscellaneous.addons worker --loglevel=INFO"
    volumes:
      - .:/netorc/
    depends_on:
      - api-services
      - redis
      - postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 100M
