#
# docker-compose.dev.yml
#
version: "3.8"
services:
  netorc-api:
    build:
      context: ./
      dockerfile: api/Dockerfile
    ports:
      - 8000:80
    restart: unless-stopped
    command: "uvicorn api.main:fastapi --reload --port 80 --host 0.0.0.0"
    volumes:
      - .:/netorc/
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M

  netorc-redis:
    image: redis:6.2-bullseye
    restart: unless-stopped
    depends_on:
      - netorc-api
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M

  netorc-postgres:
    image: postgres:15.2-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_USER: netorc
      POSTGRES_PASSWORD: netorc123
      POSTGRES_DB: netorc
    ports:
      - 5432:5432
    depends_on:
      - netorc-api
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 100M

  netorc-worker:
    build:
      context: ./
      dockerfile: worker/Dockerfile
    command: "watchmedo auto-restart -d worker/ -p '*.py' --recursive -- celery -A core.addons worker --loglevel=INFO"
    volumes:
      - .:/netorc/
    depends_on:
      - netorc-api
      - netorc-redis
      - netorc-postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 100M
