name: Docker Compose

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Local Logs
        run: mkdir logs && touch logs/netorc.log && chmod 777 logs/netorc.log
      - name: Docker Compose
        run: docker compose -d -f docker-compose.dev.yml up

