name: Testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make local log directory
        run: mkdir logs && touch logs/netorc.log
      - name: Start containers
        run: docker compose -f docker-compose.dev.yml up

